### PR TITLE
Update to X-Moto 0.6.2 and runtime to 23.08

### LINKED ISSUE #9: runtime org.freedesktop.Platform branch 20.08 is end-of-life
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

### PR DESCRIPTION
**Pull request by bbhtt**
Closes https://github.com/flathub/org.tuxfamily.XMoto/pull/10
Closes https://github.com/flathub/org.tuxfamily.XMoto/issues/9

### CODE REVIEW

**Comment by BryanQuigley** [comment]
rebuild

**Comment by bbhtt** [comment]
bot, build

DO you want to test it? If it works let me know I'll merge as the maintainer is not active here.

**Comment by BryanQuigley** [comment]
Works great.  Tested a few levels all work good.

**Comment by bbhtt** [comment]
Thanks, merging.

**Pull request merged**
