### PR TITLE
Update to X-Moto 0.6.2 and FreeDesktop SDK 22.08

### LINKED ISSUE #9: runtime org.freedesktop.Platform branch 20.08 is end-of-life
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

### PR DESCRIPTION
**Pull request by Calinou**
I can't get this to build due to the following error while building `smpeg`:

```
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[1]: *** [Makefile:416: MPEGaudio.lo] Error 63
make[1]: *** Waiting for unfinished jobs....
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[1]: *** [Makefile:416: bitwindow.lo] Error 63
make[1]: *** [Makefile:416: mpeglayer3.lo] Error 63
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[1]: *** [Makefile:416: mpegtable.lo] Error 63
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[1]: *** [Makefile:416: mpeglayer1.lo] Error 63
make[1]: *** [Makefile:416: mpeglayer2.lo] Error 63
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[1]: *** [Makefile:416: filter_2.lo] Error 63
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[1]: *** [Makefile:416: filter.lo] Error 63
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[1]: *** [Makefile:416: mpegtoraw.lo] Error 63
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[1]: *** [Makefile:416: huffmantable.lo] Error 63
make[1]: Leaving directory '/run/build/smpeg/audio'
make: *** [Makefile:867: all-recursive] Error 1
Error: module smpeg: Child process exited with code 2
```

Any ideas why? I'm not well-versed in autotools.

- This closes https://github.com/flathub/org.tuxfamily.XMoto/issues/9.

### CODE REVIEW

**Comment by julianwi** [comment]
This seems to be fixed in https://github.com/flathub/shared-modules/commit/ae74ea6577e92d3dd768575214a45df8c7b45a32. The shared-modules subproject needs to be updated to include the fix.

**Comment by Calinou** [comment]
> This seems to be fixed in [flathub/shared-modules@ae74ea6](https://github.com/flathub/shared-modules/commit/ae74ea6577e92d3dd768575214a45df8c7b45a32). The shared-modules subproject needs to be updated to include the fix.

I can confirm this works great! I tested the compiled Flatpak locally and everything works as expected. Thanks :slightly_smiling_face:

**Comment by bbhtt** [comment]
bot, build

The error is gone...

**Comment by bbhtt** [comment]
Hi, @Calinou can you please fix these?:

```
{
    "errors": [
        "toplevel-no-command"
    ],
    "warnings": [
        "module-libxdg-basedir-autotools-redundant-prefix"
    ]
}
```
The command should be the name of the executable.

**Comment by Calinou** [comment]
> Hi, @Calinou can you please fix these?:

I don't have time to look into doing this right now, so please salvage this pull request by opening a new one if you can 🙂

**Comment by bbhtt** [comment]
> > Hi, @Calinou can you please fix these?:
> 
> I don't have time to look into doing this right now, so please salvage this pull request by opening a new one if you can 🙂 

Ok, sure.  I'll open one tomorrow.

**Comment by bbhtt** [comment]
https://github.com/flathub/org.tuxfamily.XMoto/pull/11

**Pull request closed without merging**
